gui:
  showBottomLine: false
  nerdFontsVersion: "3"
quitOnTopLevelReturn: true
disableStartupPopups: true
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    #externalDiffCommand: difft --color=always --tab-width 2
os:
  editPreset: nvim
