[[manager.prepend_keymap]]
on = ["<C-s>"]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["<C-g>"]
run = 'cd --interactive'
desc = 'Interactive cd'
